export const GET_BUSINESS = "GET_BUSINESS";
export const AUTH_BUSINESS = "AUTH_BUSINESS";
export const SELF = "SELF";
export const CLEAR_BUSINESS = "CLEAR_BUSINESS";
export const UPDATE_BUSINESS = "UPDATE_BUSINESS";
export const GET_BUSINESS_BY_LOC = "GET_BUSINESS_BY_LOC";