export const ADD_JOB_SUCCESS="addjobsuccess"
export const ADD_JOB_FAILURE="addjobfailure"

export const UPDATE_JOB_SUCCESS="updatejobsuccess"
export const UPDATE_JOB_FAILURE="updatejobfailure"

export const GET_JOBS_OF_BUSINESS_SUCCESS="getjobsofbusinesssuccess"
export const GET_JOBS_OF_BUSINESS_FAILURE="getjobsofbusinessfailure"

export const DELETE_JOBS_OF_BUSINESS_SUCCESS="deletejobsofbusinesssuccess"
export const DELETE_JOBS_OF_BUSINESS_FAILURE="deletejobsofbusinessfailure"

export const GET_JOBS_OF_BUSINESS_BYID_SUCCESS="getjobsofbusinessbyidsuccess"
export const GET_JOBS_OF_BUSINESS_BYID_FAILURE="getjobsofbusinessbyidfailure"